spring.application.name=backend

spring.jpa.hibernate.ddl.auto=update

spring.datasource.url=jdbc:mysql://shalika-mysql-shalika046-3369.b.aivencloud.com:14645/paf_project_db

spring.datasource.username=dbuser
spring.datasource.password=AVNS_54mUqg-JgMhpsuE4avZ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver