spring.application.name=backend
spring.mongodb.uri=mongodb+srv://dbuser:User123@itpm.mj3w7rm.mongodb.net/UniReserver
spring.data.mongodb.auto-index-creation=true

spring.web.error.include-message=always
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.jwt.secret=ChangeThisToA32ByteOrLongerSecretKeyForJwtSigning2026
app.jwt.expiration-minutes=120
app.upload.dir=uploads/profile
app.cors.allowed-origins=http://localhost:5173

google.client.id=757745989563-gtfdp78m4u1nocd7a348lu50cr3f5fsm.apps.googleusercontent.com
