spring.application.name=unireserver-backend
spring.data.mongodb.uri=mongodb+srv://dbuser:User123@itpm.mj3w7rm.mongodb.net/UniReserver
spring.mongodb.uri=mongodb+srv://dbuser:User123@itpm.mj3w7rm.mongodb.net/UniReserver
